export function AboutPage() {
  return (
    <div className="static-page">
      <h1 className="section-heading static-page__title">About Language Helper</h1>
      <div className="static-page__body">
        <p>
          Language Helper is a workspace for Korean learners: build themed vocabulary libraries, get part-of-speech
          hints as you add words, generate English prompts from your bank, and practice by translating into Korean with
          structured feedback.
        </p>
        <p>
          Your word lists and session history stay in this browser. We designed it as a single-page studio tool with
          Fluent Sky surfaces: clear hierarchy, generous tap targets, and no clutter.
        </p>
        <p>
          Language Helper is open source.{' '}
          <a href="https://github.com/kenumeda1/learn-korean" target="_blank" rel="noopener noreferrer">
            View the source on GitHub.
          </a>
        </p>
      </div>
    </div>
  );
}

export function ContactPage() {
  return (
    <div className="static-page">
      <h1 className="section-heading static-page__title">Support</h1>
      <div className="static-page__body">
        <p>
          For bug reports, feature ideas, or questions about this app, reach out through whatever channel you use to work
          with the project maintainer (for example your team chat or repository issues).
        </p>
        <p className="static-page__hint">
          This build does not include a hosted support inbox. If you add one later, replace this section with your support
          email or form link.
        </p>
      </div>
    </div>
  );
}

export function TermsPage() {
  return (
    <div className="static-page">
      <h1 className="section-heading static-page__title">Terms of use</h1>
      <div className="static-page__body">
        <p className="static-page__hint">Last updated: April 2026</p>

        <h2>What this is</h2>
        <p>
          Language Helper is a personal vocabulary and translation practice tool for Korean learners. It is provided
          free of charge for personal, non-commercial use. By using this app you agree to these terms.
        </p>

        <h2>Acceptable use</h2>
        <p>
          You may use Language Helper for your own language learning. You may not:
        </p>
        <ul>
          <li>Use the app in a way that abuses or overloads the AI proxy (automated bulk requests, scraping, etc.)</li>
          <li>Attempt to reverse-engineer, circumvent, or exploit the server proxy</li>
          <li>Use the app for any unlawful purpose</li>
        </ul>

        <h2>AI-generated content</h2>
        <p>
          Sentences, translation feedback, and part-of-speech hints are generated by an AI model (Anthropic Claude).
          AI output can be wrong. Language Helper is a practice aid, not a certified language course or professional
          translation service. Do not rely solely on AI feedback for high-stakes language use.
        </p>

        <h2>Your data</h2>
        <p>
          Your vocabulary lists, libraries, and practice history are stored in your own browser (localStorage). We do
          not collect or store this data on our servers. Clearing your browser data will permanently delete it.
        </p>

        <h2>API requests</h2>
        <p>
          When you generate a sentence or check a translation, the relevant text is sent to Anthropic's API via a
          server-side proxy. By using these features you also agree to{' '}
          <a href="https://www.anthropic.com/legal/consumer-terms" target="_blank" rel="noopener noreferrer">
            Anthropic's usage policies
          </a>
          . Avoid entering personal or sensitive information in vocabulary inputs or translation fields.
        </p>

        <h2>No warranty</h2>
        <p>
          Language Helper is provided "as is" without warranty of any kind. We make no guarantees about uptime,
          accuracy of AI output, or fitness for any particular purpose. The service may change or become unavailable
          at any time without notice.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, we are not liable for any damages arising from your use of this
          app, including reliance on AI-generated content or loss of locally stored data.
        </p>

        <h2>Changes to these terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the app after changes are posted means you
          accept the updated terms.
        </p>
      </div>
    </div>
  );
}

export function PrivacyPage() {
  return (
    <div className="static-page">
      <h1 className="section-heading static-page__title">Privacy</h1>
      <div className="static-page__body">
        <p className="static-page__hint">Last updated: April 2026</p>

        <h2>What we collect</h2>
        <p>
          We do not collect personal information. Language Helper has no accounts, no sign-up, and no analytics.
        </p>

        <h2>Data stored in your browser</h2>
        <p>
          Your vocabulary lists, libraries, and practice history are saved in your browser's localStorage. This data
          never leaves your device — we have no access to it. Clearing your browser's site data will permanently
          delete it.
        </p>

        <h2>AI requests</h2>
        <p>
          When you use features like sentence generation or translation checking, the text you entered (vocabulary
          words and your translation attempt) is sent to Anthropic's API via a server-side proxy in order to produce
          a response. We do not log or store the content of these requests. Anthropic may retain request data
          according to their own{' '}
          <a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noopener noreferrer">
            privacy policy
          </a>
          . Avoid entering personal or sensitive information in any input field.
        </p>

        <h2>Cookies</h2>
        <p>
          Language Helper does not use cookies. A single localStorage key (<code>lh_hero_returning</code>) is set
          to remember whether you have used the app before, so the getting-started guide does not reopen on every
          visit. No tracking or advertising cookies are used.
        </p>

        <h2>Open source</h2>
        <p>
          Language Helper is open source. You can inspect exactly how the app works, including how data is stored
          and how AI requests are made, on{' '}
          <a href="https://github.com/kenumeda1/learn-korean" target="_blank" rel="noopener noreferrer">
            GitHub
          </a>
          .
        </p>

        <h2>Third parties</h2>
        <p>
          The only third-party service involved in normal app use is Anthropic (AI responses). Google Fonts is loaded
          for typography (DM Sans and Noto Sans KR); this means your browser makes a request to Google's servers
          when the page loads.
        </p>

        <h2>Children</h2>
        <p>
          Language Helper is not directed at children under 13. We do not knowingly collect data from anyone under 13.
        </p>

        <h2>Changes</h2>
        <p>
          If this policy changes materially we will update the date at the top of this page. Continued use after
          changes are posted means you accept the updated policy.
        </p>
      </div>
    </div>
  );
}
